services:
  db:
    container_name: converter-postgres
    image: postgres:16.3-alpine
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: on-failure

  backend:
    container_name: converter_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: bash -c "alembic upgrade head && uvicorn --host=0.0.0.0 --port=8000 --reload src.main:app"
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db

volumes:
  postgresdata:
